# Generated by Django 3.1.7 on 2022-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
